require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'Emparator' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])




  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'react-native-restart', :path => '../node_modules/react-native-restart'
  
  pod 'Firebase/Messaging'

# add pods for desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods




  target 'EmparatorTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end

  # use_flipper!
  # use_flipper!({ 'Flipper-Folly' => '2.3.1' }) # update this part
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'Emparator-tvOS' do
  # Pods for Emparator-tvOS

  target 'Emparator-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
